name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        # uses: cypress-io/github-action@v2
        uses: cypress-io/github-action@v2.3.8
        with:
          start: yarn serve
          wait-on: 'http://localhost:8080'
        env:
          CYPRESS_baseUrl: http://localhost:8080/
      - name: Screenshot Artifact Upload
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots/
        # Test run video was always captured, so this action uses "always()" condition
      - name: Video Artifact Upload
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: tests/e2e/videos/